{% set name = "python-poppler" %}
{% set version = "0.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/python_poppler-{{ version }}.tar.gz
  sha256: e6ca5c23ec02350bf2cef85a6bf9f1b261796436db478176f9d24fb14eeecc6a

build:
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed .  # [win]
  number: 3

requirements:
  build:
    - python                              # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - meson-python                        # [build_platform != target_platform]
    - pkg-config                          # [not win and build_platform != target_platform]
    - {{ compiler('c') }}                 # [not win]
    - {{ compiler('cxx') }}               # [not win]
    - {{ compiler('clang') }}             # [win]
  host:
    - python-build
    - meson-python
    - pkg-config
    - python
    - wheel
    - pip
    - poppler
  run:
    - python
    - poppler # poppler does not have a run-export yet

test:
  imports:
    - poppler
  commands:
    - pip check
  requires:
    - pip

about:
  summary: A Python binding to poppler-cpp
  home: https://github.com/cbrunet/python-poppler
  doc_url: https://cbrunet.net/python-poppler/
  license: GPL-2.0-only
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - '0xbe7a'
